export enum ElementType {
  BusinessActorElementType = "BusinessActor",
  BusinessCollaborationElementType = "BusinessCollaboration",
  BusinessEventElementType = "BusinessEvent",
  BusinessFunctionElementType = "BusinessFunction",
  BusinessInteractionElementType = "BusinessInteraction",
  BusinessInterfaceElementType = "BusinessInterface",
  BusinessObjectElementType = "BusinessObject",
  BusinessProcessElementType = "BusinessProcess",
  BusinessRoleElementType = "BusinessRole",
  BusinessServiceElementType = "BusinessService",
  ContractElementType = "Contract",
  LocationElementType = "Location",
  ProductElementType = "Product",
  RepresentationElementType = "Representation",
  ApplicationCollaborationElementType = "ApplicationCollaboration",
  ApplicationComponentElementType = "ApplicationComponent",
  ApplicationEventElementType = "ApplicationEvent",
  ApplicationFunctionElementType = "ApplicationFunction",
  ApplicationInteractionElementType = "ApplicationInteraction",
  ApplicationInterfaceElementType = "ApplicationInterface",
  ApplicationProcessElementType = "ApplicationProcess",
  ApplicationServiceElementType = "ApplicationService",
  DataObjectElementType = "DataObject",
  ArtifactElementType = "Artifact",
  CommunicationNetworkElementType = "CommunicationNetwork",
  CommunicationPathElementType = "CommunicationPath",
  DeviceElementType = "Device",
  InfrastructureFunctionElementType = "InfrastructureFunction",
  InfrastructureInterfaceElementType = "InfrastructureInterface",
  InfrastructureServiceElementType = "InfrastructureService",
  NetworkElementType = "Network",
  NodeElementType = "Node",
  PathElementType = "Path",
  SystemSoftwareElementType = "SystemSoftware",
  TechnologyCollaborationElementType = "TechnologyCollaboration",
  TechnologyEventElementType = "TechnologyEvent",
  TechnologyFunctionElementType = "TechnologyFunction",
  TechnologyInteractionElementType = "TechnologyInteraction",
  TechnologyInterfaceElementType = "TechnologyInterface",
  TechnologyObjectElementType = "TechnologyObject",
  TechnologyProcessElementType = "TechnologyProcess",
  TechnologyServiceElementType = "TechnologyService",
  DistributionNetworkElementType = "DistributionNetwork",
  EquipmentElementType = "Equipment",
  FacilityElementType = "Facility",
  MaterialElementType = "Material",
  AssessmentElementType = "Assessment",
  ConstraintElementType = "Constraint",
  DriverElementType = "Driver",
  GoalElementType = "Goal",
  MeaningElementType = "Meaning",
  OutcomeElementType = "Outcome",
  PrincipleElementType = "Principle",
  RequirementElementType = "Requirement",
  StakeholderElementType = "Stakeholder",
  ValueElementType = "Value",
  DeliverableElementType = "Deliverable",
  GapElementType = "Gap",
  ImplementationEventElementType = "ImplementationEvent",
  PlateauElementType = "Plateau",
  WorkPackageElementType = "WorkPackage",
  AndJunctionElementType = "AndJunction",
  JunctionElementType = "Junction",
  OrJunctionElementType = "OrJunction",
  CapabilityElementType = "Capability",
  CourseOfActionElementType = "CourseOfAction",
  ResourceElementType = "Resource",
  GroupingElementType = "Grouping",
}

export const ElementTypes = [
  ElementType.BusinessActorElementType,
  ElementType.BusinessCollaborationElementType,
  ElementType.BusinessEventElementType,
  ElementType.BusinessFunctionElementType,
  ElementType.BusinessInteractionElementType,
  ElementType.BusinessInterfaceElementType,
  ElementType.BusinessObjectElementType,
  ElementType.BusinessProcessElementType,
  ElementType.BusinessRoleElementType,
  ElementType.BusinessServiceElementType,
  ElementType.ContractElementType,
  ElementType.LocationElementType,
  ElementType.ProductElementType,
  ElementType.RepresentationElementType,
  ElementType.ApplicationCollaborationElementType,
  ElementType.ApplicationComponentElementType,
  ElementType.ApplicationEventElementType,
  ElementType.ApplicationFunctionElementType,
  ElementType.ApplicationInteractionElementType,
  ElementType.ApplicationInterfaceElementType,
  ElementType.ApplicationProcessElementType,
  ElementType.ApplicationServiceElementType,
  ElementType.DataObjectElementType,
  ElementType.ArtifactElementType,
  ElementType.CommunicationNetworkElementType,
  ElementType.CommunicationPathElementType,
  ElementType.DeviceElementType,
  ElementType.InfrastructureFunctionElementType,
  ElementType.InfrastructureInterfaceElementType,
  ElementType.InfrastructureServiceElementType,
  ElementType.NetworkElementType,
  ElementType.NodeElementType,
  ElementType.PathElementType,
  ElementType.SystemSoftwareElementType,
  ElementType.TechnologyCollaborationElementType,
  ElementType.TechnologyEventElementType,
  ElementType.TechnologyFunctionElementType,
  ElementType.TechnologyInteractionElementType,
  ElementType.TechnologyInterfaceElementType,
  ElementType.TechnologyObjectElementType,
  ElementType.TechnologyProcessElementType,
  ElementType.TechnologyServiceElementType,
  ElementType.DistributionNetworkElementType,
  ElementType.EquipmentElementType,
  ElementType.FacilityElementType,
  ElementType.MaterialElementType,
  ElementType.AssessmentElementType,
  ElementType.ConstraintElementType,
  ElementType.DriverElementType,
  ElementType.GoalElementType,
  ElementType.MeaningElementType,
  ElementType.OutcomeElementType,
  ElementType.PrincipleElementType,
  ElementType.RequirementElementType,
  ElementType.StakeholderElementType,
  ElementType.ValueElementType,
  ElementType.DeliverableElementType,
  ElementType.GapElementType,
  ElementType.ImplementationEventElementType,
  ElementType.PlateauElementType,
  ElementType.WorkPackageElementType,
  ElementType.AndJunctionElementType,
  ElementType.JunctionElementType,
  ElementType.OrJunctionElementType,
  ElementType.CapabilityElementType,
  ElementType.CourseOfActionElementType,
  ElementType.ResourceElementType,
  ElementType.GroupingElementType,
];
