export enum RelationshipType {
  Composition = "CompositionRelationship",
  Aggregation = "AggregationRelationship",
  Assignment = "AssignmentRelationship",
  Realization = "RealizationRelationship",
  Realisation = "RealisationRelationship",
  Serving = "ServingRelationship",
  UsedBy = "UsedByRelationship",
  Access = "AccessRelationship",
  Influence = "InfluenceRelationship",
  Triggering = "TriggeringRelationship",
  Flow = "FlowRelationship",
  Specialization = "SpecializationRelationship",
  Specialisation = "SpecialisationRelationship",
  Association = "AssociationRelationship",
  Junction = "JunctionRelationship",
  AndJunction = "AndJunctionRelationship",
  OrJunction = "OrJunctionRelationship",
}
