export enum ViewpointType {
  Total = "Total",
  Introductory = "Introductory",
  Organization = "Organization",
  Application_platform = "Application platform",
  Information_structure = "Information structure",
  Technology = "Technology",
  Layered = "Layered",
  Physical = "Physical",
  Product = "Product",
  Application_usage = "Application usage",
  Technology_usage = "Technology usage",
  Business_process_cooperation = "Business process cooperation",
  Application_cooperation = "Application cooperation",
  Service_realization = "Service realization",
  Implementation_and_deployment = "Implementation and deployment",
  Goal_realization = "Goal realization",
  Goal_contribution = "Goal contribution",
  Principles = "Principles",
  Requirements_realization = "Requirements realization",
  Motivation = "Motivation",
  Strategy = "Strategy",
  Capability_map = "Capability map",
  Outcome_realization = "Outcome realization",
  Resource_map = "Resource map",
  Project = "Project",
  Migration = "Migration",
  Implementation_and_migration = "Implementation and migration",
  Stakeholder = "Stakeholder",
  Actor_cooperation = "Actor cooperation",
  Business_function = "Business function",
  Business_process = "Business process",
  Application_behavior = "Application behavior",
  Application_structure = "Application structure",
  Infrastructure = "Infrastructure",
  Infrastructure_usage = "Infrastructure usage",
  Landscape_map = "Landscape map",
}

export const Viewpoints = [
  ViewpointType.Total,
  ViewpointType.Introductory,
  ViewpointType.Organization,
  ViewpointType.Application_platform,
  ViewpointType.Information_structure,
  ViewpointType.Technology,
  ViewpointType.Layered,
  ViewpointType.Physical,
  ViewpointType.Product,
  ViewpointType.Application_usage,
  ViewpointType.Technology_usage,
  ViewpointType.Business_process_cooperation,
  ViewpointType.Application_cooperation,
  ViewpointType.Service_realization,
  ViewpointType.Implementation_and_deployment,
  ViewpointType.Goal_realization,
  ViewpointType.Goal_contribution,
  ViewpointType.Principles,
  ViewpointType.Requirements_realization,
  ViewpointType.Motivation,
  ViewpointType.Strategy,
  ViewpointType.Capability_map,
  ViewpointType.Outcome_realization,
  ViewpointType.Resource_map,
  ViewpointType.Project,
  ViewpointType.Migration,
  ViewpointType.Implementation_and_migration,
  ViewpointType.Stakeholder,
  ViewpointType.Actor_cooperation,
  ViewpointType.Business_function,
  ViewpointType.Business_process,
  ViewpointType.Application_behavior,
  ViewpointType.Application_structure,
  ViewpointType.Infrastructure,
  ViewpointType.Infrastructure_usage,
  ViewpointType.Landscape_map,
]
